# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', upload_to='promo-images', verbose_name='imágen', width_field='width')),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('description', models.CharField(max_length=150, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
            ],
        ),
    ]
