# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-24 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('delicontent', '0002_auto_20160119_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name=b'slug')),
                ('title', models.CharField(max_length=200, verbose_name=b't\xc3\xadtulo')),
                ('content', markdownx.models.MarkdownxField(blank=True, help_text='Contenido de la p\xe1gina', verbose_name='contenido')),
                ('show_in_nav', models.BooleanField(verbose_name=b'mostrar en la navegaci\xc3\xb3n')),
                ('order', models.PositiveIntegerField(default=0, verbose_name=b'orden para mostrar')),
            ],
            options={
                'ordering': ('order', 'title'),
                'verbose_name': 'p\xe1gina',
                'verbose_name_plural': 'p\xe1ginas',
            },
        ),
    ]
