# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-24 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicontent', '0003_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='short_title',
            field=models.CharField(default='Cambiar!!!', help_text='Este t\xedtulo se usa para mostrar en los links', max_length=50, verbose_name='t\xedtulo corto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200, verbose_name='t\xedtulo'),
        ),
    ]
