# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-09 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliorders', '0024_auto_20160609_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='staff_comments',
            field=models.TextField(blank=True, verbose_name='notas para el usuario'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_comments',
            field=models.TextField(blank=True, verbose_name='notas del usuario'),
        ),
    ]
