# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-12 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliorders', '0025_auto_20160609_1239'),
    ]

    operations = [
    	migrations.RunSQL('ALTER TABLE account_emailaddress CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE account_emailconfirmation CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE auth_group CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE auth_group_permissions CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE auth_permission CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE auth_user CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE auth_user_groups CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE auth_user_user_permissions CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE delicontacts_customer CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE delicontacts_person CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE delicontent_promoimage CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE delidelivery_deliverymethod CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE deliorders_order CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE deliorders_orderitem CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE deliproducts_category CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE deliproducts_presentation CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE deliproducts_price CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE deliproducts_product CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE deliproducts_provider CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE django_admin_log CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE django_content_type CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE django_migrations CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE django_session CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE django_site CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE mailer_dontsendentry CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE mailer_message CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE mailer_messagelog CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE socialaccount_socialaccount CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE socialaccount_socialapp CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE socialaccount_socialapp_sites CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;'),
    	migrations.RunSQL('ALTER TABLE socialaccount_socialtoken CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;')
    ]
