# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-12 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliorders', '0026_change_collate_on_all_tables_20161111_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de entrega'),
        ),
    ]
