# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-18 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliorders', '0027_auto_20161111_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, verbose_name='direcci\xf3n de env\xedo'),
        ),
    ]
