# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-11 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliorders', '0028_auto_20161218_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delicontacts.Customer', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deliproducts.Price', verbose_name='producto'),
        ),
    ]
