# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-19 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliorders', '0030_auto_20170616_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delidelivery.DeliveryMethod', verbose_name='m\xe9todo de env\xedo'),
        ),
    ]
