from deliproducts.models import Product

p=Product();p.name=u'Aceite de Oliva La Riojana';p.description=u'Aceite de Oliva La Riojana';p.save()
p=Product();p.name=u'Aceite de oliva Las Brisas';p.description=u'Aceite de oliva Las Brisas';p.save()
p=Product();p.name=u'Aceite girasol de Naturaleza Viva';p.description=u'Aceite girasol de Naturaleza Viva';p.save()
p=Product();p.name=u'Acheto La Lomada';p.description=u'Acheto La Lomada';p.save()
p=Product();p.name=u'Alfajores de algarroba';p.description=u'Alfajores de algarroba';p.save()
p=Product();p.name=u'Algas Kombu';p.description=u'Algas Kombu';p.save()
p=Product();p.name=u'Algas Nori';p.description=u'Algas Nori';p.save()
p=Product();p.name=u'Amaranto';p.description=u'Amaranto';p.save()
p=Product();p.name=u'Arroz yamani';p.description=u'Arroz yamani';p.save()
p=Product();p.name=u'Avena arrollada';p.description=u'Avena arrollada';p.save()
p=Product();p.name=u'Azucar Schatzi';p.description=u'Azucar Schatzi';p.save()
p=Product();p.name=u'Balsamo labial cera de abeja romero y miel';p.description=u'Balsamo labial cera de abeja romero y miel';p.save()
p=Product();p.name=u'Bolsón de verduras al costo';p.description=u'Bolsón de verduras al costo';p.save()
p=Product();p.name=u'Bolsón de verduras de estación';p.description=u'Bolsón de verduras de estación';p.save()
p=Product();p.name=u'Brotes de alfalfa';p.description=u'Brotes de alfalfa';p.save()
p=Product();p.name=u'Brotes de fenogreco';p.description=u'Brotes de fenogreco';p.save()
p=Product();p.name=u'Brotes de lentejas';p.description=u'Brotes de lentejas';p.save()
p=Product();p.name=u'Budin algarroba';p.description=u'Budin algarroba';p.save()
p=Product();p.name=u'Budin de banana y avena';p.description=u'Budin de banana y avena';p.save()
p=Product();p.name=u'Cabeza de Ajo';p.description=u'Cabeza de Ajo';p.save()
p=Product();p.name=u'Café algarroba';p.description=u'Café algarroba';p.save()
p=Product();p.name=u'Café mistol';p.description=u'Café mistol';p.save()
p=Product();p.name=u'Café verde Certificado';p.description=u'Café verde Certificado';p.save()
p=Product();p.name=u'Cebada perlada';p.description=u'Cebada perlada';p.save()
p=Product();p.name=u'Centeno en grano';p.description=u'Centeno en grano';p.save()
p=Product();p.name=u'cola de caballo';p.description=u'cola de caballo';p.save()
p=Product();p.name=u'Crema hidratante con lavanda';p.description=u'Crema hidratante con lavanda';p.save()
p=Product();p.name=u'Crema hidratante con romero';p.description=u'Crema hidratante con romero';p.save()
p=Product();p.name=u'Desodorante citrus Weleda';p.description=u'Desodorante citrus Weleda';p.save()
p=Product();p.name=u'Desodorante salvia Weleda';p.description=u'Desodorante salvia Weleda';p.save()
p=Product();p.name=u'Detergente';p.description=u'Detergente';p.save()
p=Product();p.name=u'diente de león';p.description=u'diente de león';p.save()
p=Product();p.name=u'Dulce de leche Naturaleza Viva';p.description=u'Dulce de leche Naturaleza Viva';p.save()
p=Product();p.name=u'Edulcorante de stevia';p.description=u'Edulcorante de stevia';p.save()
p=Product();p.name=u'Envío';p.description=u'Envío';p.save()
p=Product();p.name=u'Esencia de vainilla';p.description=u'Esencia de vainilla';p.save()
p=Product();p.name=u'Extracto de lavanda, ideal para masajes';p.description=u'Extracto de lavanda, ideal para masajes';p.save()
p=Product();p.name=u'Galletas integrales con avena y pasas';p.description=u'Galletas integrales con avena y pasas';p.save()
p=Product();p.name=u'Galletas sin gluten con coco y limón';p.description=u'Galletas sin gluten con coco y limón';p.save()
p=Product();p.name=u'Galletas sin gluten con naranja y chia';p.description=u'Galletas sin gluten con naranja y chia';p.save()
p=Product();p.name=u'Germen de trigo';p.description=u'Germen de trigo';p.save()
p=Product();p.name=u'Ginecologia natural de bolsillo';p.description=u'Ginecologia natural de bolsillo';p.save()
p=Product();p.name=u'Hamburguesas x6 garbanzos';p.description=u'Hamburguesas x6 garbanzos';p.save()
p=Product();p.name=u'Hamburguesas x6 lentejas';p.description=u'Hamburguesas x6 lentejas';p.save()
p=Product();p.name=u'Hamburguesas x6 mijo';p.description=u'Hamburguesas x6 mijo';p.save()
p=Product();p.name=u'Harina de algarroba';p.description=u'Harina de algarroba';p.save()
p=Product();p.name=u'Harina de arroz';p.description=u'Harina de arroz';p.save()
p=Product();p.name=u'Harina de centeno';p.description=u'Harina de centeno';p.save()
p=Product();p.name=u'Harina de lino Naturaleza Viva';p.description=u'Harina de lino Naturaleza Viva';p.save()
p=Product();p.name=u'Harina de soja Naturaleza Viva';p.description=u'Harina de soja Naturaleza Viva';p.save()
p=Product();p.name=u'Harina de trigo integral';p.description=u'Harina de trigo integral';p.save()
p=Product();p.name=u'Harina de trigo integral Naturaleza Viva';p.description=u'Harina de trigo integral Naturaleza Viva';p.save()
p=Product();p.name=u'Huevos de campo';p.description=u'Huevos de campo';p.save()
p=Product();p.name=u'Huevos de campo 1/2 doc';p.description=u'Huevos de campo 1/2 doc';p.save()
p=Product();p.name=u'Huevos por maple';p.description=u'Huevos por maple';p.save()
p=Product();p.name=u'Jugo de manzana';p.description=u'Jugo de manzana';p.save()
p=Product();p.name=u'Jugo de pera y manzana';p.description=u'Jugo de pera y manzana';p.save()
p=Product();p.name=u'Libro Cuerpo de mujer sabiduria de mujer';p.description=u'Libro Cuerpo de mujer sabiduria de mujer';p.save()
p=Product();p.name=u'Libro Luna Roja';p.description=u'Libro Luna Roja';p.save()
p=Product();p.name=u'Limones certificados';p.description=u'Limones certificados';p.save()
p=Product();p.name=u'Lunario';p.description=u'Lunario';p.save()
p=Product();p.name=u'Maca Kalpa';p.description=u'Maca Kalpa';p.save()
p=Product();p.name=u'Manual de ginecología natural';p.description=u'Manual de ginecología natural';p.save()
p=Product();p.name=u'Manzanas';p.description=u'Manzanas';p.save()
p=Product();p.name=u'Mascabo';p.description=u'Mascabo';p.save()
p=Product();p.name=u'Mate cocido Tucangua';p.description=u'Mate cocido Tucangua';p.save()
p=Product();p.name=u'Mermelada de arándanos';p.description=u'Mermelada de arándanos';p.save()
p=Product();p.name=u'Mermelada de cayote';p.description=u'Mermelada de cayote';p.save()
p=Product();p.name=u'Mermelada de durazno';p.description=u'Mermelada de durazno';p.save()
p=Product();p.name=u'Mermelada de manzana';p.description=u'Mermelada de manzana';p.save()
p=Product();p.name=u'Mermelada frambuesa';p.description=u'Mermelada frambuesa';p.save()
p=Product();p.name=u'Mermelada frutilla';p.description=u'Mermelada frutilla';p.save()
p=Product();p.name=u'Mermelada frutos rojos';p.description=u'Mermelada frutos rojos';p.save()
p=Product();p.name=u'Miel El Arbol';p.description=u'Miel El Arbol';p.save()
p=Product();p.name=u'Miel El Arbol algarrobo';p.description=u'Miel El Arbol algarrobo';p.save()
p=Product();p.name=u'Miel El Arbol atamiski';p.description=u'Miel El Arbol atamiski';p.save()
p=Product();p.name=u'Miel El Arbol chilca';p.description=u'Miel El Arbol chilca';p.save()
p=Product();p.name=u'Miel El Arbol juda';p.description=u'Miel El Arbol juda';p.save()
p=Product();p.name=u'Miel El Arbol Multifloral';p.description=u'Miel El Arbol Multifloral';p.save()
p=Product();p.name=u'Mijo';p.description=u'Mijo';p.save()
p=Product();p.name=u'Multiuso';p.description=u'Multiuso';p.save()
p=Product();p.name=u'Naranjas';p.description=u'Naranjas';p.save()
p=Product();p.name=u'Nueces';p.description=u'Nueces';p.save()
p=Product();p.name=u'Pan integral';p.description=u'Pan integral';p.save()
p=Product();p.name=u'Pan integral con semillas';p.description=u'Pan integral con semillas';p.save()
p=Product();p.name=u'Pasas de uva';p.description=u'Pasas de uva';p.save()
p=Product();p.name=u'Pasas de uva envasada';p.description=u'Pasas de uva envasada';p.save()
p=Product();p.name=u'pasas de uva envasda';p.description=u'pasas de uva envasda';p.save()
p=Product();p.name=u'Pastas secas cinta';p.description=u'Pastas secas cinta';p.save()
p=Product();p.name=u'Pastas secas codito';p.description=u'Pastas secas codito';p.save()
p=Product();p.name=u'Pastas secas tirabuzon';p.description=u'Pastas secas tirabuzon';p.save()
p=Product();p.name=u'Pircas Negras cabernet';p.description=u'Pircas Negras cabernet';p.save()
p=Product();p.name=u'Pircas Negras torrontes';p.description=u'Pircas Negras torrontes';p.save()
p=Product();p.name=u'Polen de flores';p.description=u'Polen de flores';p.save()
p=Product();p.name=u'Polenta del campo';p.description=u'Polenta del campo';p.save()
p=Product();p.name=u'Poleo';p.description=u'Poleo';p.save()
p=Product();p.name=u'Poroto de soja';p.description=u'Poroto de soja';p.save()
p=Product();p.name=u'Porotos blancos';p.description=u'Porotos blancos';p.save()
p=Product();p.name=u'Porotos colorados';p.description=u'Porotos colorados';p.save()
p=Product();p.name=u'Porotos negros';p.description=u'Porotos negros';p.save()
p=Product();p.name=u'Prepizzas';p.description=u'Prepizzas';p.save()
p=Product();p.name=u'Protectores diarios Kit';p.description=u'Protectores diarios Kit';p.save()
p=Product();p.name=u'Protectores mamarios';p.description=u'Protectores mamarios';p.save()
p=Product();p.name=u'Protectotes diarios';p.description=u'Protectotes diarios';p.save()
p=Product();p.name=u'Pure tomates El Peregrino';p.description=u'Pure tomates El Peregrino';p.save()
p=Product();p.name=u'Rebozador de arroz certificado';p.description=u'Rebozador de arroz certificado';p.save()
p=Product();p.name=u'Repelente de citronela homeopatico';p.description=u'Repelente de citronela homeopatico';p.save()
p=Product();p.name=u'Sal del himalaya';p.description=u'Sal del himalaya';p.save()
p=Product();p.name=u'Sal Macrozen';p.description=u'Sal Macrozen';p.save()
p=Product();p.name=u'Salvado de avena';p.description=u'Salvado de avena';p.save()
p=Product();p.name=u'Salvado de trigo';p.description=u'Salvado de trigo';p.save()
p=Product();p.name=u'Semilla de amaranto';p.description=u'Semilla de amaranto';p.save()
p=Product();p.name=u'Semilla de girasol pelado con descuento';p.description=u'Semilla de girasol pelado con descuento';p.save()
p=Product();p.name=u'Semilla de lino';p.description=u'Semilla de lino';p.save()
p=Product();p.name=u'Semilla de sesamo integral';p.description=u'Semilla de sesamo integral';p.save()
p=Product();p.name=u'Semilla girasol pelado';p.description=u'Semilla girasol pelado';p.save()
p=Product();p.name=u'Semilla sesamo integral';p.description=u'Semilla sesamo integral';p.save()
p=Product();p.name=u'Spirulina Organikal en polvo';p.description=u'Spirulina Organikal en polvo';p.save()
p=Product();p.name=u'Suavizante para Ropa';p.description=u'Suavizante para Ropa';p.save()
p=Product();p.name=u'Tabaco Sayri';p.description=u'Tabaco Sayri';p.save()
p=Product();p.name=u'Te cedrón Heredia';p.description=u'Te cedrón Heredia';p.save()
p=Product();p.name=u'Te Earl Grey Heredia';p.description=u'Te Earl Grey Heredia';p.save()
p=Product();p.name=u'Te menta Heredia';p.description=u'Te menta Heredia';p.save()
p=Product();p.name=u'Te negro Heredia';p.description=u'Te negro Heredia';p.save()
p=Product();p.name=u'Te negro Tucangua';p.description=u'Te negro Tucangua';p.save()
p=Product();p.name=u'Te rojo Tucangua';p.description=u'Te rojo Tucangua';p.save()
p=Product();p.name=u'Te rosella Tucangua';p.description=u'Te rosella Tucangua';p.save()
p=Product();p.name=u'Te surtido Heredia';p.description=u'Te surtido Heredia';p.save()
p=Product();p.name=u'Te verde con limon y naranja Heredia';p.description=u'Te verde con limon y naranja Heredia';p.save()
p=Product();p.name=u'Te verde Tucangua';p.description=u'Te verde Tucangua';p.save()
p=Product();p.name=u'Tofu';p.description=u'Tofu';p.save()
p=Product();p.name=u'Tomates Cherrys';p.description=u'Tomates Cherrys';p.save()
p=Product();p.name=u'Tomates secos';p.description=u'Tomates secos';p.save()
p=Product();p.name=u'Trigo en grano';p.description=u'Trigo en grano';p.save()
p=Product();p.name=u'Unguento dolores musculares (28cc)';p.description=u'Unguento dolores musculares (28cc)';p.save()
p=Product();p.name=u'Vinagre con especias La Lomada';p.description=u'Vinagre con especias La Lomada';p.save()
p=Product();p.name=u'Vinagre de manzana La Lomada';p.description=u'Vinagre de manzana La Lomada';p.save()
p=Product();p.name=u'Vinagre de uva';p.description=u'Vinagre de uva';p.save()
p=Product();p.name=u'Yerba mate 4 Caminos Certificada';p.description=u'Yerba mate 4 Caminos Certificada';p.save()
p=Product();p.name=u'Yerba mate Guidaí';p.description=u'Yerba mate Guidaí';p.save()
p=Product();p.name=u'Yerba mate La Jactancia';p.description=u'Yerba mate La Jactancia';p.save()
