# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delidelivery', '0003_auto_20150802_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymethod',
            name='delivery_day',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Mi\xe9rcoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'S\xe1bado'), (6, 'Domingo')], default=2, verbose_name='d\xeda de entrega'),
            preserve_default=False,
        ),
    ]
