# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-01 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delidelivery', '0004_auto_20160201_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='delivery_price',
            field=models.DecimalField(decimal_places=4, default=20.0, max_digits=20, verbose_name='precio de envío'),
        ),
    ]
