# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-20 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delidelivery', '0005_deliverymethod_delivery_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notas'),
        ),
    ]
