# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-03 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicontacts', '0017_auto_20160119_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_confirmed_tf',
            field=models.DateTimeField(null=True, verbose_name='\xfaltima confirmaci\xf3n de ventana de entrega'),
        ),
    ]
