# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-11 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delicontacts', '0018_auto_20160403_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='delicontacts.Person')),
                ('is_subscribed', models.BooleanField(default=True, verbose_name='est\xe1 suscripto')),
                ('related_customer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriber', to='delicontacts.Customer', verbose_name='cliente actual')),
            ],
            options={
                'verbose_name': 'suscriptor de novedades',
                'verbose_name_plural': 'suscriptores de novedades',
            },
            bases=('delicontacts.person',),
        )
    ]
