# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-11 19:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delicontacts', '0019_auto_20170211_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='associated_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuario vinculado'),
        ),
    ]
