# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-05 14:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delicontacts', '0020_auto_20170211_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='associated_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario vinculado'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='prefered_delivery_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delidelivery.DeliveryMethod', verbose_name='forma de env\xedo preferida'),
        ),
    ]
