# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-01-07 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicontacts', '0021_auto_20180205_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='person_ptr',
        ),
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='related_customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='subscribed_to_newsletter',
            field=models.BooleanField(default=True, verbose_name='suscripto a newsletter'),
        ),
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
    ]
