# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliproducts', '0024_auto_20160120_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='nombre'),
        ),
    ]
