# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliproducts', '0026_product_inactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inactive',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
    ]
