# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliproducts', '0028_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
    ]
