# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliproducts', '0029_category_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order',), 'verbose_name': 'categor\xeda', 'verbose_name_plural': 'categor\xedas'},
        ),
    ]
