# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliproducts', '0030_auto_20160201_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
    ]
