# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-03 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliproducts', '0031_price_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('product__name',), 'verbose_name': 'precio', 'verbose_name_plural': 'precios'},
        ),
    ]
