# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-03 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliproducts', '0032_auto_20160403_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripci\xf3n'),
        ),
    ]
