# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-03 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliproducts', '0033_auto_20160403_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
        migrations.AddField(
            model_name='price',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='destacado'),
        ),
    ]
