# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-03 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliproducts', '0034_auto_20160403_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='deliproducts.Category', verbose_name='categor\xeda padre'),
        ),
    ]
