# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-18 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliproducts', '0035_auto_20160403_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True, help_text='descripci\xf3n que se muestra en el detalle de producto', verbose_name='descripci\xf3n larga'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='descripci\xf3n que se muestra en los listados de producto', verbose_name='descripci\xf3n'),
        ),
    ]
